kind: Deployment
apiVersion: apps/v1
metadata:
  name: openapi-platform
  namespace: risk-sgp-prod
  labels:
    app.kubernetes.io/name: openapi-platform
    app.kubernetes.io/env: prod
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: openapi-platform
      app.kubernetes.io/env: prod
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openapi-platform
        app.kubernetes.io/env: prod
        creator: wangjie
    spec:
      imagePullSecrets:
        - name: acr-regcred
      containers:
        - name: openapi-platform
          image: 01ai-registry.cn-shanghai.cr.aliyuncs.com/data-risk/openapi-platform:IMAGE_TAG
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: openapi-platform-env-config  # 注意匹配 ConfigMap 名称
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 4000m
              memory: 8192Mi
            requests:
              cpu: 500m
              memory: 1024Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations: { }
  labels:
    app.kubernetes.io/env: prod
    app.kubernetes.io/name: openapi-platform
  name: openapi-platform
  namespace: risk-sgp-prod
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/env: prod
    app.kubernetes.io/name: openapi-platform
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: { }
  labels:
    app.kubernetes.io/env: prod
    app.kubernetes.io/name: openapi-platform
  name: openapi-platform
  namespace: risk-sgp-prod
spec:
  ingressClassName: mse-internal
  rules:
    - host: openapi.lingyiwanwu.net
      http:
        paths:
          - backend:
              service:
                name: openapi-platform
                port:
                  number: 3000
            path: /
            pathType: Prefix